/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaz;

import Logica.Compania;
import Logica.MongoConnection;
import Logica.Pelicula;
import java.util.ArrayList;
import java.util.List;
import java.util.StringTokenizer;
import javax.swing.JOptionPane;

/**
 *
 * @author Daniel
 */
public class cCompania extends javax.swing.JFrame {

    /**
     * Creates new form cCompania
     */
    public cCompania() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel_nombrePelicula = new javax.swing.JLabel();
        jLabel_nombreDirector = new javax.swing.JLabel();
        jLabel_genero = new javax.swing.JLabel();
        jTextField_nombreCompania = new javax.swing.JTextField();
        jTextField_anio = new javax.swing.JTextField();
        jTextField_paginaWeb = new javax.swing.JTextField();
        jButton_guardar1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel_nombrePelicula.setText("Nombre de la compañia:");

        jLabel_nombreDirector.setText("Año de la fundación:");

        jLabel_genero.setText("Sitio web oficial:");

        jButton_guardar1.setText("Guardar");
        jButton_guardar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_guardar1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel_nombrePelicula)
                    .addComponent(jLabel_genero)
                    .addComponent(jLabel_nombreDirector, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton_guardar1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jTextField_paginaWeb)
                    .addComponent(jTextField_nombreCompania)
                    .addComponent(jTextField_anio, javax.swing.GroupLayout.DEFAULT_SIZE, 255, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_nombreCompania, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_nombrePelicula))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_anio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_nombreDirector))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_paginaWeb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_genero))
                .addGap(18, 18, 18)
                .addComponent(jButton_guardar1)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private boolean VerificaString(String cadena, int mode) {

        boolean verificar = false;
        if (mode == -1) {

            cadena = cadena.replace(" ", "");
            for (int i = 0; i < cadena.length(); i++) {

                if (Character.isLetter(cadena.charAt(i))) {
                    verificar = true;

                }//Fin del for
                else {
                    return false;
                }
            }//Fin del if
        } else if (mode == 0) {

            cadena = cadena.replace(" ", "");
            for (int i = 0; i < cadena.length(); i++) {

                if (Character.isLetter(cadena.charAt(i)) || Character.isDigit(cadena.charAt(i))) {
                    verificar = true;

                }//Fin del for
                else {
                    return false;
                }
            }//Fin del if
        } else {

            for (int i = 0; i < cadena.length(); i++) {

                if (Character.isDigit(cadena.charAt(i))) {

                    verificar = true;

                }//Fin del for
                else {
                    return false;
                }
            }//Fin del if
        }
        return verificar;
    }//Fin del metodo VerificaString

    private void jButton_guardar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_guardar1ActionPerformed
        if ((VerificaString(jTextField_nombreCompania.getText(), 0)) && (VerificaString(jTextField_anio.getText(), 1))) {

            if (jTextField_paginaWeb.getText().equals("")) {
                Compania C = new Compania(jTextField_nombreCompania.getText(), Integer.parseInt(jTextField_anio.getText()));

                MongoConnection MC = new MongoConnection();
                MC.guardarCompania(C);
                JOptionPane.showMessageDialog(rootPane, "Se guardo la compañia exitosamente");
            } else {
                
                Compania C = new Compania(jTextField_nombreCompania.getText(), Integer.parseInt(jTextField_anio.getText()),jTextField_paginaWeb.getText());
                
                MongoConnection MC = new MongoConnection();
                MC.guardarCompania(C);
                JOptionPane.showMessageDialog(rootPane, "Se guardo la pelicula exitosamente");
            }
        } else {
            JOptionPane.showMessageDialog(rootPane, "Error revise los datos ingresados");
        }


    }//GEN-LAST:event_jButton_guardar1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(cCompania.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(cCompania.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(cCompania.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(cCompania.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new cCompania().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_guardar1;
    private javax.swing.JLabel jLabel_genero;
    private javax.swing.JLabel jLabel_nombreDirector;
    private javax.swing.JLabel jLabel_nombrePelicula;
    private javax.swing.JTextField jTextField_anio;
    private javax.swing.JTextField jTextField_nombreCompania;
    private javax.swing.JTextField jTextField_paginaWeb;
    // End of variables declaration//GEN-END:variables
}
