/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaz;

import Logica.MongoConnection;
import java.util.ArrayList;
import java.util.List;
import java.util.StringTokenizer;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import org.bson.Document;

/**
 *
 * @author Daniel
 */
public class dPelicula extends javax.swing.JFrame {

    /**
     * Creates new form dPelicula
     */
    public dPelicula() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jTextField_genero = new javax.swing.JTextField();
        jLabel_actores = new javax.swing.JLabel();
        jLabel_paisProduccion = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jTextField_paisProduccion = new javax.swing.JTextField();
        jLabel_franquicia = new javax.swing.JLabel();
        jButton_Buscar = new javax.swing.JButton();
        jTextField_franquicia = new javax.swing.JTextField();
        jLabel_companíaProductora = new javax.swing.JLabel();
        jLabel_nombrePelicula = new javax.swing.JLabel();
        jTextField_companíaProductora = new javax.swing.JTextField();
        jTextField_nombrePelicula = new javax.swing.JTextField();
        jLabel_anio = new javax.swing.JLabel();
        jLabel_nombreDirector = new javax.swing.JLabel();
        jTextField_anio = new javax.swing.JTextField();
        jTextField_nombreDirector = new javax.swing.JTextField();
        jLabel_minutos = new javax.swing.JLabel();
        jLabel_genero = new javax.swing.JLabel();
        jTextField_minutos = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jButton_Borrar = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel_actores.setText("Actores (separar con ,):");

        jLabel_paisProduccion.setText("Pais de producción:");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jLabel_franquicia.setText("Franquicia (opcional):");

        jButton_Buscar.setText("Filtrar");
        jButton_Buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_BuscarActionPerformed(evt);
            }
        });

        jLabel_companíaProductora.setText("Compañia productora:");

        jLabel_nombrePelicula.setText("Nombre de la pelicula:");

        jLabel_anio.setText("Año de producción:");

        jLabel_nombreDirector.setText("Nombre del director:");

        jLabel_minutos.setText("Minutos que dura:");

        jLabel_genero.setText("Genero de la pelicula:");

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre pelicula", "Nombre director", "Genero", "Pais", "Franquicia", "Compañia productora", "Año", "Minutos", "Actores"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable2.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        jTable2.setAutoscrolls(false);
        jScrollPane3.setViewportView(jTable2);
        if (jTable2.getColumnModel().getColumnCount() > 0) {
            jTable2.getColumnModel().getColumn(0).setMinWidth(125);
            jTable2.getColumnModel().getColumn(1).setMinWidth(125);
            jTable2.getColumnModel().getColumn(2).setMinWidth(125);
            jTable2.getColumnModel().getColumn(3).setMinWidth(125);
            jTable2.getColumnModel().getColumn(4).setMinWidth(125);
            jTable2.getColumnModel().getColumn(5).setMinWidth(125);
            jTable2.getColumnModel().getColumn(8).setMinWidth(1000);
        }

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 18, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 529, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jButton_Borrar.setText("Borrar");
        jButton_Borrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_BorrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel_nombreDirector)
                                            .addComponent(jLabel_genero))
                                        .addGap(20, 20, 20))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLabel_nombrePelicula)
                                        .addGap(18, 18, 18)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jTextField_nombrePelicula, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 270, Short.MAX_VALUE)
                                    .addComponent(jTextField_nombreDirector, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextField_genero)))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(jLabel_actores)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jScrollPane1))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(jLabel_paisProduccion)
                                    .addGap(30, 30, 30)
                                    .addComponent(jTextField_paisProduccion))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(jLabel_franquicia)
                                    .addGap(20, 20, 20)
                                    .addComponent(jTextField_franquicia))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel_companíaProductora)
                                        .addComponent(jLabel_anio))
                                    .addGap(16, 16, 16)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jTextField_anio, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(jLabel_minutos)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(jTextField_minutos, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(jTextField_companíaProductora)))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(22, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(207, 207, 207)
                        .addComponent(jButton_Buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton_Borrar)
                        .addGap(250, 250, 250))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField_nombrePelicula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel_nombrePelicula))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField_nombreDirector, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel_nombreDirector))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel_genero)
                            .addComponent(jTextField_genero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel_paisProduccion)
                            .addComponent(jTextField_paisProduccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(8, 8, 8)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel_franquicia)
                            .addComponent(jTextField_franquicia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel_companíaProductora)
                            .addComponent(jTextField_companíaProductora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel_anio)
                            .addComponent(jTextField_anio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel_minutos)
                            .addComponent(jTextField_minutos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel_actores, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton_Borrar)
                    .addComponent(jButton_Buscar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_BuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_BuscarActionPerformed
        Document doc = createDBObjectPelicula();
        MongoConnection MC = new MongoConnection();
        List<Document> F = null;
        if (doc == null) {
            F = MC.leerTodoPelicula();
        } else {
            F = MC.leerPelicula(doc);
        }

        DefaultTableModel dfm = (DefaultTableModel) jTable2.getModel();

        int filas = dfm.getRowCount();
        for (int i = 1; i <= filas; i++) {
            dfm.removeRow(0);
        }

        for (Document docs : F) {
            dfm.addRow(new Object[]{docs.getString("nombrePelicula"), docs.getString("nombreDirector"), docs.getString("genero"),
                docs.getString("paisDeProduccion"), docs.getString("franquicia"), docs.getString("companíaProductora"),
                docs.getInteger("año"), docs.getInteger("minutos"), docs.get("actores").toString()});
        }
    }//GEN-LAST:event_jButton_BuscarActionPerformed

    private void refrescar() {
        MongoConnection MC = new MongoConnection();
        List<Document> F = null;

        F = MC.leerTodoPelicula();

        DefaultTableModel dfm = (DefaultTableModel) jTable2.getModel();

        int filas = dfm.getRowCount();
        for (int i = 1; i <= filas; i++) {
            dfm.removeRow(0);
        }

        for (Document docs : F) {
            dfm.addRow(new Object[]{docs.getString("nombrePelicula"), docs.getString("nombreDirector"), docs.getString("genero"),
                docs.getString("paisDeProduccion"), docs.getString("franquicia"), docs.getString("companíaProductora"),
                docs.getInteger("año"), docs.getInteger("minutos"), docs.get("actores").toString()});
        }
    }

    private void jButton_BorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_BorrarActionPerformed
        int row = jTable2.getSelectedRow();

        if (row != -1) {

            MongoConnection MC = new MongoConnection();
            if (jTable2.getValueAt(row, 4) == null) {

                Document D = createDBObjectPelicula((String) jTable2.getValueAt(row, 0), (String) jTable2.getValueAt(row, 1),
                        (String) jTable2.getValueAt(row, 2), (String) jTable2.getValueAt(row, 3),
                        "",(String) jTable2.getValueAt(row, 5), (int) jTable2.getValueAt(row, 6), (int) jTable2.getValueAt(row, 7),
                        (String) jTable2.getValueAt(row, 8));

                MC.borrarPelicula(D);
            } else {
                Document D = createDBObjectPelicula((String) jTable2.getValueAt(row, 0), (String) jTable2.getValueAt(row, 1),
                        (String) jTable2.getValueAt(row, 2), (String) jTable2.getValueAt(row, 3),
                        (String)jTable2.getValueAt(row, 4),(String) jTable2.getValueAt(row, 5), (int) jTable2.getValueAt(row, 6), 
                        (int) jTable2.getValueAt(row, 7),(String) jTable2.getValueAt(row, 8));

                MC.borrarPelicula(D);
            }
            JOptionPane.showMessageDialog(rootPane, "Se elimino la pelicula");
            refrescar();

        } else {
            JOptionPane.showMessageDialog(rootPane, "Error: Selecione una fila");
        }

    }//GEN-LAST:event_jButton_BorrarActionPerformed

    private Document createDBObjectPelicula() {
        Document docBuilder = new Document();
        boolean entre = false;
        if (jTextField_nombrePelicula.getText().equals("") == false) {
            docBuilder.append("nombrePelicula", jTextField_nombrePelicula.getText());
            entre = true;
        }
        if (jTextField_nombreDirector.getText().equals("") == false) {
            docBuilder.append("nombreDirector", jTextField_nombreDirector.getText());
            entre = true;
        }
        if (jTextField_genero.getText().equals("") == false) {
            docBuilder.append("genero", jTextField_genero.getText());
            entre = true;
        }
        if (jTextField_paisProduccion.getText().equals("") == false) {
            docBuilder.append("paisDeProduccion", jTextField_paisProduccion.getText());
            entre = true;
        }
        if (jTextField_franquicia.getText().equals("") == false) {
            docBuilder.append("franquicia", jTextField_franquicia.getText());
            entre = true;
        }
        if (jTextField_companíaProductora.getText().equals("") == false) {
            docBuilder.append("companíaProductora", jTextField_companíaProductora.getText());
            entre = true;
        }
        if (jTextField_anio.getText().equals("") == false) {
            docBuilder.append("año", jTextField_anio.getText());
            entre = true;
        }
        if (jTextField_minutos.getText().equals("") == false) {
            docBuilder.append("minutos", jTextField_minutos.getText());
            entre = true;
        }
        if (jTextArea1.getText().equals("") == false) {

            String actores = jTextArea1.getText();
            jTextArea1.setText(actores);
            StringTokenizer tokens = new StringTokenizer(actores, ",");

            List<String> LS = new ArrayList<String>();

            while (tokens.hasMoreTokens()) {
                LS.add(tokens.nextToken());
            }

            Document DocActores = new Document();

            DocActores.append("$all", LS);
            docBuilder.append("actores", DocActores);
        }
        
        if (entre) {
            return docBuilder;
        }
        return null;

    }//Fin del metodo leerDBObjectPelicula

    private Document createDBObjectPelicula(String nombrePelicua, String nombreDirector,
            String genero, String pais, String franquicia, String compania, int anio,
            int minutos, String actores) {
        Document docBuilder = new Document();

        docBuilder.append("nombrePelicula", nombrePelicua);
        docBuilder.append("nombreDirector", nombreDirector);
        docBuilder.append("genero", genero);

        docBuilder.append("paisDeProduccion", pais);
        if (franquicia.equals("") == false) {
            docBuilder.append("franquicia", franquicia);
        }

        docBuilder.append("companíaProductora", compania);
        docBuilder.append("año", anio);
        docBuilder.append("minutos", minutos);
        
        actores = actores.substring(1, actores.length()-1);
        actores = actores.replaceAll(", ", ",");
        System.out.print(actores);
        StringTokenizer tokens = new StringTokenizer(actores, ",");
        
        while (tokens.hasMoreTokens()) {
            docBuilder.append("actores", tokens.nextToken());
        }
        System.err.println(docBuilder.toJson());
        return docBuilder;

    }//Fin del metodo leerDBObjectPelicula

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(dPelicula.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(dPelicula.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(dPelicula.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(dPelicula.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new dPelicula().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_Borrar;
    private javax.swing.JButton jButton_Buscar;
    private javax.swing.JLabel jLabel_actores;
    private javax.swing.JLabel jLabel_anio;
    private javax.swing.JLabel jLabel_companíaProductora;
    private javax.swing.JLabel jLabel_franquicia;
    private javax.swing.JLabel jLabel_genero;
    private javax.swing.JLabel jLabel_minutos;
    private javax.swing.JLabel jLabel_nombreDirector;
    private javax.swing.JLabel jLabel_nombrePelicula;
    private javax.swing.JLabel jLabel_paisProduccion;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField_anio;
    private javax.swing.JTextField jTextField_companíaProductora;
    private javax.swing.JTextField jTextField_franquicia;
    private javax.swing.JTextField jTextField_genero;
    private javax.swing.JTextField jTextField_minutos;
    private javax.swing.JTextField jTextField_nombreDirector;
    private javax.swing.JTextField jTextField_nombrePelicula;
    private javax.swing.JTextField jTextField_paisProduccion;
    // End of variables declaration//GEN-END:variables
}
