/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaz;

import Logica.MongoConnection;
import java.util.ArrayList;
import java.util.List;
import java.util.StringTokenizer;
import javax.swing.table.DefaultTableModel;
import org.bson.Document;

/**
 *
 * @author Daniel
 */
public class rPelicula extends javax.swing.JFrame {

    /**
     * Creates new form rPelicula
     */
    public rPelicula() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField_nombrePelicula = new javax.swing.JTextField();
        jLabel_paisProduccion = new javax.swing.JLabel();
        jLabel_anio = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel_nombreDirector = new javax.swing.JLabel();
        jTextField_anio = new javax.swing.JTextField();
        jTextField_paisProduccion = new javax.swing.JTextField();
        jTextField_nombreDirector = new javax.swing.JTextField();
        jLabel_franquicia = new javax.swing.JLabel();
        jLabel_minutos = new javax.swing.JLabel();
        jButton_Filtrar = new javax.swing.JButton();
        jLabel_genero = new javax.swing.JLabel();
        jTextField_franquicia = new javax.swing.JTextField();
        jTextField_minutos = new javax.swing.JTextField();
        jLabel_companíaProductora = new javax.swing.JLabel();
        jLabel_nombrePelicula = new javax.swing.JLabel();
        jTextField_genero = new javax.swing.JTextField();
        jTextField_companíaProductora = new javax.swing.JTextField();
        jLabel_actores = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jButton_Back1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel_paisProduccion.setText("Pais de producción:");

        jLabel_anio.setText("Año de producción:");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jLabel_nombreDirector.setText("Nombre del director:");

        jLabel_franquicia.setText("Franquicia:");

        jLabel_minutos.setText("Minutos que dura:");

        jButton_Filtrar.setText("Filtrar");
        jButton_Filtrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_FiltrarActionPerformed(evt);
            }
        });

        jLabel_genero.setText("Genero de la pelicula:");

        jLabel_companíaProductora.setText("Compañia productora:");

        jLabel_nombrePelicula.setText("Nombre de la pelicula:");

        jLabel_actores.setText("Actores (separar con ,):");

        jScrollPane4.setAutoscrolls(true);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre Pelicula", "Nombre Director", "Genero", "País", "Franquicia", "Companía productora", "Año", "Minutos", "Actores"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable2.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        jTable2.setAutoscrolls(false);
        jScrollPane4.setViewportView(jTable2);
        if (jTable2.getColumnModel().getColumnCount() > 0) {
            jTable2.getColumnModel().getColumn(0).setMinWidth(115);
            jTable2.getColumnModel().getColumn(0).setMaxWidth(100);
            jTable2.getColumnModel().getColumn(1).setMinWidth(120);
            jTable2.getColumnModel().getColumn(5).setMinWidth(150);
            jTable2.getColumnModel().getColumn(8).setMinWidth(200);
        }

        jButton_Back1.setText("...");
        jButton_Back1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Back1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel_nombreDirector)
                                            .addComponent(jLabel_genero))
                                        .addGap(20, 20, 20))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLabel_nombrePelicula)
                                        .addGap(18, 18, 18)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jTextField_nombrePelicula, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 270, Short.MAX_VALUE)
                                    .addComponent(jTextField_nombreDirector, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextField_genero)))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(jLabel_actores)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jScrollPane1))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(jLabel_paisProduccion)
                                    .addGap(30, 30, 30)
                                    .addComponent(jTextField_paisProduccion))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel_companíaProductora)
                                        .addComponent(jLabel_anio)
                                        .addComponent(jLabel_franquicia))
                                    .addGap(16, 16, 16)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jTextField_franquicia)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jTextField_anio, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(jLabel_minutos)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(jTextField_minutos, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(jTextField_companíaProductora)))))
                        .addGap(28, 28, 28)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 539, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton_Back1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(189, 189, 189)
                        .addComponent(jButton_Filtrar, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField_nombrePelicula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel_nombrePelicula))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField_nombreDirector, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel_nombreDirector))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel_genero)
                            .addComponent(jTextField_genero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel_paisProduccion)
                            .addComponent(jTextField_paisProduccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel_franquicia)
                            .addComponent(jTextField_franquicia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel_companíaProductora)
                            .addComponent(jTextField_companíaProductora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel_anio)
                            .addComponent(jTextField_anio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel_minutos)
                            .addComponent(jTextField_minutos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel_actores, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_Filtrar)
                    .addComponent(jButton_Back1))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_FiltrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_FiltrarActionPerformed
        Document doc = createDBObjectPelicula();
        MongoConnection MC = new MongoConnection();
        List<Document> F = null;
        if (doc == null) {
            F = MC.leerTodoPelicula();
        } else {
            F = MC.leerPelicula(doc);
        }

        DefaultTableModel dfm = (DefaultTableModel) jTable2.getModel();
        int filas = dfm.getRowCount();
        for (int i = 1; i <= filas; i++) {
            dfm.removeRow(0);
        }
        for (Document docs : F) {
            dfm.addRow(new Object[]{docs.getString("nombrePelicula"), docs.getString("nombreDirector"), docs.getString("genero"),
                docs.getString("paisDeProduccion"), docs.getString("franquicia"), docs.getString("companíaProductora"),
                docs.getInteger("año"), docs.getInteger("minutos"), docs.get("actores").toString()});
        }
    }//GEN-LAST:event_jButton_FiltrarActionPerformed

    private void jButton_Back1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Back1ActionPerformed
        PeliculaInterfaz PI = new PeliculaInterfaz();
        PI.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton_Back1ActionPerformed

    private Document createDBObjectPelicula() {
        Document docBuilder = new Document();
        boolean entre = false;
        if (jTextField_nombrePelicula.getText().equals("") == false) {
            docBuilder.append("nombrePelicula", jTextField_nombrePelicula.getText());
            entre = true;
        }
        if (jTextField_nombreDirector.getText().equals("") == false) {
            docBuilder.append("nombreDirector", jTextField_nombreDirector.getText());
            entre = true;
        }
        if (jTextField_genero.getText().equals("") == false) {
            docBuilder.append("genero", jTextField_genero.getText());
            entre = true;
        }
        if (jTextField_paisProduccion.getText().equals("") == false) {
            docBuilder.append("paisDeProduccion", jTextField_paisProduccion.getText());
            entre = true;
        }
        if (jTextField_franquicia.getText().equals("") == false) {
            docBuilder.append("franquicia", jTextField_franquicia.getText());
            entre = true;
        }
        if (jTextField_companíaProductora.getText().equals("") == false) {
            docBuilder.append("companíaProductora", jTextField_companíaProductora.getText());
            entre = true;
        }
        if (jTextField_anio.getText().equals("") == false) {
            docBuilder.append("año", Integer.parseInt(jTextField_anio.getText()));
            entre = true;
        }
        if (jTextField_minutos.getText().equals("") == false) {
            docBuilder.append("minutos", Integer.parseInt(jTextField_minutos.getText()));
            entre = true;
        }
        if (jTextArea1.getText().equals("") == false) {

           String actores = jTextArea1.getText();
            jTextArea1.setText(actores);
            StringTokenizer tokens = new StringTokenizer(actores, ",");

            List<String> LS = new ArrayList<String>();

            while (tokens.hasMoreTokens()) {
                LS.add(tokens.nextToken());
            }

            Document DocActores = new Document();

            DocActores.append("$all", LS);
            docBuilder.append("actores", DocActores);
            entre= true;
        
        }
        if (entre) {
            return docBuilder;
        }
        return null;

    }//Fin del metodo leerDBObjectPelicula

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(rPelicula.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(rPelicula.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(rPelicula.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(rPelicula.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new rPelicula().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_Back;
    private javax.swing.JButton jButton_Back1;
    private javax.swing.JButton jButton_Filtrar;
    private javax.swing.JLabel jLabel_actores;
    private javax.swing.JLabel jLabel_anio;
    private javax.swing.JLabel jLabel_companíaProductora;
    private javax.swing.JLabel jLabel_franquicia;
    private javax.swing.JLabel jLabel_genero;
    private javax.swing.JLabel jLabel_minutos;
    private javax.swing.JLabel jLabel_nombreDirector;
    private javax.swing.JLabel jLabel_nombrePelicula;
    private javax.swing.JLabel jLabel_paisProduccion;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField_anio;
    private javax.swing.JTextField jTextField_companíaProductora;
    private javax.swing.JTextField jTextField_franquicia;
    private javax.swing.JTextField jTextField_genero;
    private javax.swing.JTextField jTextField_minutos;
    private javax.swing.JTextField jTextField_nombreDirector;
    private javax.swing.JTextField jTextField_nombrePelicula;
    private javax.swing.JTextField jTextField_paisProduccion;
    // End of variables declaration//GEN-END:variables
}
